# Generated by Django 4.0 on 2021-12-15 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='What is the name of this coop', max_length=100)),
                ('address', models.CharField(blank=True, help_text='what is the address of this coop', max_length=500, null=True)),
                ('building', models.CharField(help_text='What building is this coop in', max_length=100)),
                ('vegan', models.BooleanField(help_text='is this a vegan coop')),
                ('num_dining', models.IntegerField(help_text='how many dining members does this coop have')),
                ('num_housing', models.IntegerField(help_text='how many housing members does this coop have')),
                ('hours_needed', models.IntegerField(help_text='how many hours a week do members have to work')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tnumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('pronouns', models.CharField(max_length=20)),
                ('time_aid', models.IntegerField()),
                ('missed_jobes', models.IntegerField()),
                ('coop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.coops')),
            ],
        ),
        migrations.CreateModel(
            name='Workchart_slots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=10)),
                ('meal', models.CharField(max_length=20)),
                ('crew', models.BooleanField()),
                ('required_members', models.IntegerField()),
                ('pic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=100)),
                ('position_description', models.CharField(max_length=500)),
                ('hours_required', models.IntegerField()),
                ('emergency_contact', models.BooleanField()),
                ('all_osca', models.BooleanField()),
                ('coop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.coops')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.members')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_budget', models.IntegerField()),
                ('remaining_budget', models.IntegerField()),
                ('coop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.coops')),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('severity', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium-Low'), (2, 'Medium'), (3, 'Medium-High'), (4, 'High')], default=0)),
                ('allowed_in_coop', models.BooleanField()),
                ('coop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.coops')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.members')),
            ],
        ),
    ]
