# Generated by Django 4.0 on 2021-12-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='name',
            new_name='preferred_name',
        ),
    ]
