# Generated by Django 4.0 on 2021-12-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_name_members_preferred_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergies',
            new_name='Allergy',
        ),
        migrations.RenameModel(
            old_name='Coops',
            new_name='Coop',
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='Officers',
            new_name='Officer',
        ),
        migrations.RenameModel(
            old_name='Workchart_slots',
            new_name='Workchart_slot',
        ),
    ]
