# Generated by Django 4.0 on 2022-01-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_member_email_alter_member_missed_jobes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='all_osca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officer',
            name='emergency_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officer',
            name='position_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
