# Generated by Django 3.2.10 on 2022-01-22 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_officer_all_osca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('mid_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CookShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_selection', models.IntegerField(choices=[(1, 'Full cook shift'), (2, 'First half of cook shift'), (3, 'Second half of cook shift')], default=1, verbose_name='Shift_Times')),
                ('is_head_cook', models.BooleanField()),
                ('cook_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cook')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.member')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrewShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_pic', models.BooleanField()),
                ('crew_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.crew')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.member')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_of_the_day', models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Pizza Night'), (5, 'Specail Meal'), (6, 'Commando Crew')], default=2, verbose_name='Meal_Choices')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, verbose_name='Day_Choices')),
                ('cook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cook')),
                ('coop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.coop')),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.crew')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protein', models.CharField(max_length=300)),
                ('vegetable', models.CharField(max_length=300)),
                ('starch', models.CharField(max_length=300)),
                ('dr_protein', models.CharField(blank=True, max_length=300, null=True)),
                ('dr_vegetable', models.CharField(blank=True, max_length=300, null=True)),
                ('dr_starch', models.CharField(blank=True, max_length=300, null=True)),
                ('meat', models.BooleanField(default=False, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('headCook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Workchart_slot',
        ),
        migrations.AddField(
            model_name='meal',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.menu'),
        ),
        migrations.AddField(
            model_name='crew',
            name='pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.crewshift'),
        ),
        migrations.AddField(
            model_name='cook',
            name='head_cook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cookshift'),
        ),
    ]
