# Generated by Django 4.0 on 2022-01-18 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_officer_all_osca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workchart_slot',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='workchart_slot',
            name='required_members',
        ),
        migrations.AddField(
            model_name='workchart_slot',
            name='coop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.coop'),
        ),
        migrations.AddField(
            model_name='workchart_slot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workchart_slot',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.member'),
        ),
        migrations.AddField(
            model_name='workchart_slot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protein', models.CharField(max_length=300)),
                ('vegetable', models.CharField(max_length=300)),
                ('starch', models.CharField(max_length=300)),
                ('dr_protein', models.CharField(blank=True, max_length=300, null=True)),
                ('dr_vegetable', models.CharField(blank=True, max_length=300, null=True)),
                ('dr_starch', models.CharField(blank=True, max_length=300, null=True)),
                ('meat', models.BooleanField(default=False, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('headCook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.member')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_of_the_day', models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Pizza Night'), (5, 'Specail Meal'), (6, 'Commando Crew')], default=2, verbose_name='Meal_Choices')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], default=1, verbose_name='Day_Choices')),
                ('crew_required_members', models.IntegerField()),
                ('cook_required_members', models.IntegerField()),
                ('coop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.coop')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.menu')),
            ],
        ),
        migrations.AlterField(
            model_name='workchart_slot',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.meal'),
        ),
    ]
