# Generated by Django 4.0 on 2022-01-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_cookshift_shift_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookshift',
            name='shift_selection',
            field=models.IntegerField(choices=[(1, 'Full cook shift and head cook'), (2, 'Full cook shift'), (3, 'First half of cook shift'), (4, 'Second first half of cook shift'), (5, 'Second half of cook shift'), (6, 'Second second half of cook shift')], default=1, verbose_name='Shift_Times'),
        ),
    ]
