# Generated by Django 4.0 on 2022-01-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_cookshift_shift_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cook', models.BooleanField()),
                ('is_pic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkChartRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('cook', models.BooleanField()),
                ('pic', models.BooleanField()),
                ('friday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday', to='catalog.shift')),
                ('monday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday', to='catalog.shift')),
                ('saturday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturday', to='catalog.shift')),
                ('sunday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday', to='catalog.shift')),
                ('thursday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday', to='catalog.shift')),
                ('tuesday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday', to='catalog.shift')),
                ('wednesday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday', to='catalog.shift')),
            ],
        ),
        migrations.RemoveField(
            model_name='cookshift',
            name='cook_obj',
        ),
        migrations.RemoveField(
            model_name='cookshift',
            name='member',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='crewshift',
            name='crew_obj',
        ),
        migrations.RemoveField(
            model_name='crewshift',
            name='member',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='cook',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='crew',
        ),
        migrations.DeleteModel(
            name='Cook',
        ),
        migrations.DeleteModel(
            name='CookShift',
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='CrewShift',
        ),
        migrations.AddField(
            model_name='shift',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.meal'),
        ),
        migrations.AddField(
            model_name='shift',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.member'),
        ),
    ]
