# Generated by Django 4.0 on 2022-01-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_shift_workchartrow_remove_cookshift_cook_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workchartrow',
            name='coop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.coop'),
        ),
    ]
